#include<iostream>
#include<cstdlib>
#include<ctime>
#include<stdio.h>
using namespace std;

int main()
{
    int random, guess, counter=0;

    srand((unsigned) time(0));

    random = (rand()%100)+1;

    cout<<"A number has been generated by the system try to guess it"<<endl;

    while(true)
    {
        counter++;
        cout<<"Enter your guess"<<endl;
        cin>>guess;

        if(guess>random)
        {
            cout<<"Your guess is high, try again"<<endl;
        }
        else if(guess<random)
        {
            cout<<"Your guess is low, try again"<<endl;
        }
        else
        {
            break;
        }
    }
    cout<<"Congrates, YOu have guessed the number in "<<counter<<" attempts"<<endl;
}