//guessing game using while loop
#include<iostream>
#include<iomanip>
#include<stdio.h>
#include<ctime>
#include<cstdlib>
using namespace std;

int main()
{
    int randomnum, guess, counter;
    counter  = 0;

    srand((unsigned) time(0));   // for generate a true random number

    randomnum = (rand() % 100) + 1;         // it means values from 1-100

    cout<<"a random number is generated by the system try to guess it"<<endl;

    while(true)
    {
        counter++;   //to count the attempts
        cout<<"Enter the guess number"<<endl;
        cin>>guess;

        if(guess > randomnum)
        {
            cout<<"You guessed high, retry"<<endl;
        }
        else if(guess < randomnum)
        {
            cout<<"You guessed low, retry"<<endl;
        }
        else{
            break;
        }
    }
    cout<<"Congrats you guessed it, in "<<counter<<" attempts"<<endl;
}
